### ISSUE TITLE
启动错误

### ISSUE THREAD

**Issue by WHYwanghuayang** [productdevbook/nuxt3-app#22]
### Environment

未知

### Describe the bug

500
Cannot read properties of undefined (reading 'map')
at Module.normalizePlugins (file:///D:/Nuxt/github/nuxt3-app/.nuxt/dist/server/server.mjs:181:28)
at $id_59c78dfd (file:///D:/Nuxt/github/nuxt3-app/.nuxt/dist/server/server.mjs:28:39)
at async __instantiateModule__ (file:///D:/Nuxt/github/nuxt3-app/.nuxt/dist/server/server.mjs:1021:3)

### Additional context

未知

### Logs

```shell
未知
```

**Comment by productdevbook** [comment]
node and npm version ?
